---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=2.0.0.2
install:
  - sudo pip install ansible==$ANSIBLE_VERSION
script:
  - ansible --version
  - export ANSIBLE_ROLES_PATH="../"
  - ansible-playbook -i hosts --syntax-check tests/vagrant.yml
