---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=1.9.5
  - ANSIBLE_VERSION=2.0.1.0
install:
  - sudo pip install ansible==$ANSIBLE_VERSION
script:
  - ansible --version
  - ansible-playbook -i tests/hosts --syntax-check docker.yml
